# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

  paths:
    include:
      - webapp/webapp.front
    exclude:
      - azure-pipelines-front.yml

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build and push containers
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Druni-acr'
              repository: 'webapp.front'
              command: 'buildAndPush'
              Dockerfile: 'webapp/webapp.front/Dockerfile'
              buildContext: 'webapp/webapp.front/'
              tags: | 
                $(Build.BuildId)
                latest

      
  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - deployment: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        environment: Desarrollo.default
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: KubernetesManifest@0
                  displayName: Creacion del deployment
                  inputs:
                    action: deploy                    
                    manifests: ./webapp/.k8s/webapp.front.*.yml
                    containers: drnacr.azurecr.io/webapp.front:$(Build.BuildId)
