apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default  
spec:
  replicas: 3
  containers:
  - name: dnsutils    
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always   
