apiVersion: v1
kind: Secret
metadata:
  name: drnacr-key
type: Opaque
data:
  docker-server: ZHJuYWNyLmF6dXJlY3IuaW8=
  docker-email: am9zZS5oZXJuYW5kZXpAZHJ1bmkuZXM=
  docker-username: NTFhYjdmMTQtZDkzYS00N2FjLWIwNzQtMDA1YTA4OTJjNzBm
  docker-password: MFVXMHhBLXh2aWFyLi1mYXMuYjFEekUxNEdtS19MfmJZWQ==