apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql

  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      # hostname: mssqlinst
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001   
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: "4096Mi"
            cpu: "500m"
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "pnNBKBTr9Mfz"
        volumeMounts:
        - name: mssqldb
          mountPath: "/var/opt/mssql"

      volumes:
      - name: mssqldb
        vsphereVolume:          
          volumePath: "[3PAR_RAID5_V1] discos/sqldata"
          fsType: ext4          
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  # type: LoadBalancer