apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-front

spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp-front

  template:
    metadata:
      labels:
        app: webapp-front
    spec:
      imagePullSecrets:
      - name: drnacr-key
      containers:      
      - name: webapp-front
        env:
          - name: WEBAPPBACKURL
            valueFrom:
              configMapKeyRef:
                key: WEBAPPBACKURL
                name: webapp
        image: drnacr.azurecr.io/webapp.front:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443
