apiVersion: v1
kind: Service
metadata:
  name: webapp-from
spec:
  type: LoadBalancer
  selector:
    app: webapp-front
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
