apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-back

spec:
  selector:
    matchLabels:
      app: webapp-back

  template:
    metadata:
      labels:
        app: webapp-back
    spec:
      imagePullSecrets:
      - name: drnacr-key
      containers:
      - name: webapp-back
        image: drnacr.azurecr.io/webapp.back:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443
