apiVersion: v1
kind: Service
metadata:
  name: webapp-back
spec:
  selector:
    app: webapp-back
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
